### ISSUE TITLE
ModuleNotFoundError <types>

### ISSUE THREAD

**Issue by kristoffer-paulsson** [kayhayen/Nuitka#108]
Hi thank you for making Nuitka, I like it. Had a problem compiling it.

Macos High Sierra, virtualenv, python3.7.0, Nuitka 0.5.33rc7

I have a hello world program in Python, using:

ython -m nuitka --recurse-all --standalone program.py

I get the following error:

Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/inspect.py", line 35, in <module>
    import dis
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/dis.py", line 4, in <module>
    import types
ModuleNotFoundError: No module named 'types'

**Comment by kayhayen** [comment]
Why did you skip filling out the issue template. Without knowing what CPython it is, esp. those hello world problems are impossible to debug.

**Comment by kayhayen** [comment]
Lack of feedback
