### ISSUE TITLE
Build for Raspberry pi ?

### ISSUE THREAD

**Issue by stuaxo** [kayhayen/Nuitka#13]
Hi,
    Is there any chance you can add a build for raspbian to the packages you provide ?

I had a quick go installing the one in their repo, it's version 0.5.5.3 and my codebase is python 3.4, I got a bunch of errors that made me think trying a newer version might be an idea.

S

```
$ python `which nuitka` --recurse-all lumen_client/lumenclient.py 
WARNING:root:Problem at '<SourceCodeReference to lumen_client/lumenclient.py:8>' with Call(func=Attribute(value=Name(id='uvloop', ctx=Load()), attr='EventLoopPolicy', ctx=Load()), args=[], keywords=[]).
WARNING:root:Problem at '<SourceCodeReference to lumen_client/lumenclient.py:8>' with Call(func=Attribute(value=Name(id='asyncio', ctx=Load()), attr='set_event_loop_policy', ctx=Load()), args=[Call(func=Attribute(value=Name(id='uvloop', ctx=Load()), attr='EventLoopPolicy', ctx=Load()), args=[], keywords=[])], keywords=[]).
WARNING:root:Problem at '<SourceCodeReference to lumen_client/lumenclient.py:8>' with Expr(value=Call(func=Attribute(value=Name(id='asyncio', ctx=Load()), attr='set_event_loop_policy', ctx=Load()), args=[Call(func=Attribute(value=Name(id='uvloop', ctx=Load()), attr='EventLoopPolicy', ctx=Load()), args=[], keywords=[])], keywords=[])).
Traceback (most recent call last):
  File "/usr/bin/nuitka", line 156, in <module>
    MainControl.main()
  File "/usr/share/nuitka/nuitka/MainControl.py", line 660, in main
    filename = filename
  File "/usr/share/nuitka/nuitka/MainControl.py", line 72, in createNodeTree
    is_main  = not Options.shallMakeModule()
  File "/usr/share/nuitka/nuitka/tree/Building.py", line 1242, in buildModuleTree
    is_main         = is_main
  File "/usr/share/nuitka/nuitka/tree/Building.py", line 1201, in createModuleTree
    is_main     = is_main
  File "/usr/share/nuitka/nuitka/tree/Building.py", line 896, in buildParseTree
    source_ref = source_ref
  File "/usr/share/nuitka/nuitka/tree/Helpers.py", line 168, in buildStatementsNode
    statements = buildNodeList(provider, nodes, source_ref, allow_none = True)
  File "/usr/share/nuitka/nuitka/tree/Helpers.py", line 130, in buildNodeList
    entry = buildNode(provider, node, node_source_ref, allow_none)
  File "/usr/share/nuitka/nuitka/tree/Helpers.py", line 91, in buildNode
    source_ref = source_ref
  File "/usr/share/nuitka/nuitka/tree/Building.py", line 761, in buildExprOnlyNode
    expression = buildNode( provider, node.value, source_ref ),
  File "/usr/share/nuitka/nuitka/tree/Helpers.py", line 91, in buildNode
    source_ref = source_ref
  File "/usr/share/nuitka/nuitka/tree/ReformulationCallExpressions.py", line 42, in buildCallNode
    positional_args = buildNodeList(provider, node.args, source_ref)
  File "/usr/share/nuitka/nuitka/tree/Helpers.py", line 130, in buildNodeList
    entry = buildNode(provider, node, node_source_ref, allow_none)
  File "/usr/share/nuitka/nuitka/tree/Helpers.py", line 91, in buildNode
    source_ref = source_ref
  File "/usr/share/nuitka/nuitka/tree/ReformulationCallExpressions.py", line 61, in buildCallNode
    list_star_arg = buildNode(provider, node.starargs, source_ref, True)
AttributeError: 'Call' object has no attribute 'starargs'

```

**Comment by kayhayen** [comment]
>
> Hi,
> Is there any chance you can add a build for raspbian to the packages you
> provide ?
>
> I had a quick go installing the one in their repo, it's version 0.5.5.3
> and my codebase is python 3.4, I got a bunch of errors that made me think
> trying a newer version might be an idea.
>
I didn't know that such a package existed. This is indeed pretty ancient,
for Python3 I would definitely use newer ones, I think Python2 was pretty
much always good.

If it's trivial to do, I am open, but you might want to contact "them" to
update their repo?

Yours,
Kay

**Comment by stuaxo** [comment]
raspbian is based on debian, so I the provided build is based on whatever is in debian.

I guess, since debian don't release very often that explains how the really old build.

(In the same way, I had to build my own python3.5, I guess I should also build Nuitka if I end up using it).

**Comment by kayhayen** [comment]
Ok, let me close this then. Debian will soon release Stretch with updated Nuitka.

**Comment by stuaxo** [comment]
Thanks for looking at this :)
