### ISSUE TITLE
Hangs when compiling subprocess.wait "line 1055, in wait"

### ISSUE THREAD

**Issue by BenTearzz** [kayhayen/Nuitka#130]
**Nuitka Version:** 0.5.32.8
**Python Version:** 3.6.5

When I try to compile my script using `nuitka --standalone file.py`, it starts compiling until it suddenly hits a certain point where it hangs and Windows Shell Process starts taking up 80%+ of my CPU. In my script I import the subprocess module. But when it tries to compile the subprocess module it hangs at subprocess.wait and never gets done compiling.

```
Traceback (most recent call last):
  File "C:\Users\Tearzz\AppData\Local\Programs\Python\Python36\lib\site-packages\nuitka\__main__.py", line 218, in <module>
    main()
  File "C:\Users\Tearzz\AppData\Local\Programs\Python\Python36\lib\site-packages\nuitka\__main__.py", line 212, in main
    MainControl.main()
  File "C:\Users\Tearzz\AppData\Local\Programs\Python\Python36\lib\site-packages\nuitka\MainControl.py", line 815, in main
    main_module = main_module
  File "C:\Users\Tearzz\AppData\Local\Programs\Python\Python36\lib\site-packages\nuitka\MainControl.py", line 727, in compileTree
    quiet       = not Options.isShowScons()
  File "C:\Users\Tearzz\AppData\Local\Programs\Python\Python36\lib\site-packages\nuitka\MainControl.py", line 594, in runScons
    return SconsInterface.runScons(options, quiet), options
  File "C:\Users\Tearzz\AppData\Local\Programs\Python\Python36\lib\site-packages\nuitka\build\SconsInterface.py", line 283, in runScons
    return subprocess.call(scons_command, shell = False) == 0
  File "C:\Users\Tearzz\AppData\Local\Programs\Python\Python36\lib\subprocess.py", line 269, in call
    return p.wait(timeout=timeout)
  File "C:\Users\Tearzz\AppData\Local\Programs\Python\Python36\lib\subprocess.py", line 1055, in wait
```

**Comment by kayhayen** [comment]
Can you post the output with --scow-scons ?

**Comment by BenTearzz** [comment]
That did it, realized GCC took quite some time to run on all of the files which is the reason.
