### ISSUE TITLE
Problems with getting started: WinError 2

### ISSUE THREAD

**Issue by stehol01** [kayhayen/Nuitka#15]
Hy nuitka people,

I'm a newby to nuitka and i would really like to try it, but i'm running into some troubles. If i try to compile a simple HelloWorld.py file i always end up with the following error:

C:\Python34\Scripts>nuitka --module HelloWorld.py
Traceback (most recent call last):
  File "C:\Python34\Scripts\nuitka", line 195, in <module>
    MainControl.main()
  File "C:\Python34\Lib\site-packages\nuitka\MainControl.py", line 737, in main
    main_module = main_module
  File "C:\Python34\Lib\site-packages\nuitka\MainControl.py", line 654, in compi
leTree
    quiet       = not Options.isShowScons()
  File "C:\Python34\Lib\site-packages\nuitka\MainControl.py", line 524, in runSc
ons
    return SconsInterface.runScons(options, quiet), options
  File "C:\Python34\Lib\site-packages\nuitka\build\SconsInterface.py", line 215,
 in runScons
    return subprocess.call(scons_command, shell = False) == 0
  File "C:\Python34\lib\subprocess.py", line 535, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Python34\lib\subprocess.py", line 848, in __init__
    restore_signals, start_new_session)
  File "C:\Python34\lib\subprocess.py", line 1104, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] Das System kann die angegebene Datei nicht finde
n

Here is what i did to install nuitka: I downloaded the nuitka installation .msi file for windows x64 and python 3.4. I started the installation and added the path to the python 3.4 installation. Corresponding to that I use python 3.4 for testing nuitka (i also use a python 3.6 version with anaconda, altough i have a python 2.7 installation). I also installed Visual Studio 2015 professional. The same error occurs if i try to test this in python 3.6.

I found a similar post to this problem here http://bugs.nuitka.net/msg1381 but it seems that this question was not answered, at least i cant find it. 

Furthermore i would like to obtain a corresponding c++ file out of my .py file. What is the best way to obtain this in nuitka? I'm not sure about this...

Would be nice if someone could help me! :)

**Comment by kayhayen** [comment]
Please read the user manual. You need to have a Python2 installation too.
