### ISSUE TITLE
Compiling python code that uses six.py somewhere in the import chain

### ISSUE THREAD

**Issue by guttinasrinivas** [kayhayen/Nuitka#56]
Steps:
1. Compile any code that has six.py in it's import chain - e.g. direct usage or imports some module which eventually imports six.py
e.g. 
```
~/temp/glances $ nuitka --python-version=3.5 --portable --recurse-all /usr/bin/glances 
Nuitka:WARNING:Unresolved '__import__' call at '/home/gsjy/.local/lib/python3.5/site-packages/six.py:82' may require use of '--recurse-directory'.
```
2. Try running the generated code.
Result:
```
~/temp/glances$ glances.dist/glances.exe 
Traceback (most recent call last):
  File "/home/gsjy/temp/glances/glances.dist/glances", line 5, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/home/gsjy/temp/glances/glances.dist/pkg_resources/__init__.py", line 51, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/home/gsjy/temp/glances/glances.dist/pkg_resources/extern/__init__.py", line 43, in load_module
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
KeyError: 'six'
```
*  Nuitka version 0.5.28.1, Python 3.5.2 and Python 2.7.12 on Ubuntu 16.04 and Windows 10
*  Python installed and kept up to date by the APT, nuitka installed and managed by pip
*  No virtualenv
*  Looks like issue is not a regression.

**Comment by BYCHEN** [comment]
I met the same problem, too.

**Comment by kayhayen** [comment]
Can you try out develop branch. I recall that I did some work around its
meta path based importer, but I am unsure now.

**Comment by BYCHEN** [comment]
Hi @kabrepos ,

Upgrade to version 0.5.28.2 that will fix this issue. I can build the executable file. 

 I appreciated your time and effort.

**Comment by alex-pobeditel-2004** [comment]
> 
> Can you try out develop branch. I recall that I did some work around its meta path based importer, but I am unsure now.

Hello @kayhayen!
The problem has resurrected and persists now at least on Nuitka 0.6.1 ... 0.6.3 (python 3.6.1) - I tried to build my tool with dulwich library (git on python) on Windows 10 and Debian 9.4:
```
 nuitka --follow-imports --standalone --output-dir=".\build" C:\Users\user\git\myrepo\mytool.py
Nuitka:WARNING:Unresolved '__import__' call at 'C:\Program Files\Python36\lib\site-packages\urllib3\packages\six.py:82' may require use of '--include-plugin-directory' or '--include-plugin-files'.
IndexError: list index out of range:
  File "C:\Program Files\Python36\lib\site-packages\nuitka\build\SingleExe.scons", line 477:
    env = createEnvironment(compiler_tools=compiler_tools)
  File "C:\Program Files\Python36\lib\site-packages\nuitka\build\SingleExe.scons", line 462:
    **args
  File "C:\Program Files\Python36\lib\site-packages\nuitka\build\inline_copy\lib\scons-3.0.4\SCons\Environment.py", line 982:
    apply_tools(self, tools, toolpath)
  File "C:\Program Files\Python36\lib\site-packages\nuitka\build\inline_copy\lib\scons-3.0.4\SCons\Environment.py", line 107:
    env.Tool(tool)
  File "C:\Program Files\Python36\lib\site-packages\nuitka\build\inline_copy\lib\scons-3.0.4\SCons\Environment.py", line 1789:
    tool(self)
  File "C:\Program Files\Python36\lib\site-packages\nuitka\build\inline_copy\lib\scons-3.0.4\SCons\Tool\__init__.py", line 299:
    self.generate(env, *args, **kw)
  File "C:\Program Files\Python36\lib\site-packages\nuitka\build\inline_copy\lib\scons-3.0.4\SCons\Tool\default.py", line 40:
    for t in SCons.Tool.tool_list(env['PLATFORM'], env):
  File "C:\Program Files\Python36\lib\site-packages\nuitka\build\inline_copy\lib\scons-3.0.4\SCons\Tool\__init__.py", line 1271:
    c_compiler = FindTool(c_compilers, env) or c_compilers[0]
  File "C:\Program Files\Python36\lib\site-packages\nuitka\build\inline_copy\lib\scons-3.0.4\SCons\Tool\__init__.py", line 1172:
    if t.exists(env):
  File "C:\Program Files\Python36\lib\site-packages\nuitka\build\inline_copy\lib\scons-3.0.4\SCons\Tool\msvc.py", line 292:
    return msvc_exists(env)
  File "C:\Program Files\Python36\lib\site-packages\nuitka\build\inline_copy\lib\scons-3.0.4\SCons\Tool\MSCommon\vc.py", line 759:
    vcs = cached_get_installed_vcs(env)
  File "C:\Program Files\Python36\lib\site-packages\nuitka\build\inline_copy\lib\scons-3.0.4\SCons\Tool\MSCommon\vc.py", line 524:
    ret = get_installed_vcs(env)
  File "C:\Program Files\Python36\lib\site-packages\nuitka\build\inline_copy\lib\scons-3.0.4\SCons\Tool\MSCommon\vc.py", line 535:
    VC_DIR = find_vc_pdir(ver)
  File "C:\Program Files\Python36\lib\site-packages\nuitka\build\inline_copy\lib\scons-3.0.4\SCons\Tool\MSCommon\vc.py", line 344:
    comps = find_vc_pdir_vswhere(msvc_version)
  File "C:\Program Files\Python36\lib\site-packages\nuitka\build\inline_copy\lib\scons-3.0.4\SCons\Tool\MSCommon\vc.py", line 306:
    vc_pdir = os.path.join(vsdir[0], 'VC')
```

**Comment by kayhayen** [comment]
@alex-pobeditel-2004 What makes you think this is the original issue, because it is not. Report a new issue.
