### ISSUE TITLE
ModuleNotFoundError: No module named 'PyQt5'

### ISSUE THREAD

**Issue by brupelo** [kayhayen/Nuitka#72]
Kay, 

Hello, I've created a little test for you to play with:

 - git clone https://github.com/brupelo/nuitka_tests
 - Instructions to reproduce [here](https://github.com/brupelo/nuitka_tests/blob/master/pyqt/test1/readme.txt)

Please confirm me if you're able to reproduce it on your side, if not, just let me know how can I help you
to narrow it down.

Thanks in advance.

**Comment by kayhayen** [comment]
So this code:

`from PyQt5.Qt import *`

for me it throws (now?)  with this command:

`LANG=C /c/Python36_64/python ../../../Py2C/bin/nuitka --run main.py`

Traceback (most recent call last):
  File "C:\Users\kayha\repos\nuitka_tests\pyqt\test1\main.py", line 2, in <module>
    from PyQt5.Qt import *
ImportError: DLL load failed: (translated) The specified module could not be found

(Note: The LANG=C is ineffective to Windows, so I had to manually translate the error message.)

I am going this way, as the `import *` and all should have nothing to do with the `main.py ` code going wrong here. And I really wonder, why it could.  I do get that something magic happens for PyQt5.Qt that makes it a non-module, at least not the one which comes from:

$ ls /c/Python36_64/lib/site-packages/PyQt5/Qt
bin/  plugins/  qml/  resources/  translations/

That is not usable for star import, it actually wouldn't import anything. Which might have been what is happening for you in standalone mode, which would hint to another bug there, although a tough one to catch. Nuitka really has no way of knowing that this is not what you will get. The plugin we have will be able to. For standalone mode or even --recurse-to=PyQt5, the import might be hard resolved to that, where as non-standalone will actually look up.

Back to what I am seeing, the "*" import is actually implemented and supported pretty well. But it might be that the assumption that we are having a module returned might be wrong, although I thought that was an error that is catched.

**Comment by kayhayen** [comment]
I had a look at the PyQt5 package file itself:

```
import os as _os

_path = _os.path.dirname(__file__) + '\\Qt\\bin;' + _os.environ['PATH']
_os.environ['PATH'] = _path
```

That is a perfect example of why the subdirectories scan for standalone has to be done. People do this crap just so their DLLs will load from sub folders. 

But what I was looking for, was something that would make PyQt5.Qt be handled differently, but that didn't exist. But I noticed now, there is both the directory and the Qt.pyd, and although I think that the order of loading should be correct, maybe it is not.

This has multiple levels to it. During the scan when Nuitka does attempt to recurse it, and at run time.

As you can see, even with no recursion, Nuitka still goes wrong. And that would normally have to be CPython itself?! With --python-flag=-v one sees more, this:

```
# C:\Python36_64\lib\site-packages\PyQt5\__pycache__\__init__.cpython-36.pyc matches C:\Python36_64\lib\site-packages\PyQt5\__init__.py
# code object from 'C:\\Python36_64\\lib\\site-packages\\PyQt5\\__pycache__\\__init__.cpython-36.pyc'
import 'PyQt5' # <_frozen_importlib_external.SourceFileLoader object at 0x0000015E76E14AC8>
Traceback (most recent call last):
  File "C:\Users\kayha\repos\nuitka_tests\pyqt\test1\main.py", line 6, in <module>
    import PyQt5.Qt
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 658, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 922, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: DLL load failed: Das angegebene Modul wurde nicht gefunden.
```

So here I am starting to think that `__spec__` may have something to do with it, but for main programs that one is "None" with both. Something strange is going on here.

Yours,
Kay

**Comment by kayhayen** [comment]
I have eliminated the meta path based loader of Nuitka, which is in fact being asked about a "spec" in find_spec() for the PyQt5.Qt module, and returns "None". Just to be sure, we are not supposed to do anything else there.

This highlights also that the meta path based loader is registered more often than necessary. I am using the table of it to find "__main__", but not going through "__import__", so the actual meta path based loader ought to be removed in that instance. But it surely is not a big problem of any sorts, but were it also used for single modules, it would be bad for the eco system.

But I am not understanding, what the difference is, and what DLL load is actually throwing the error there. Using strace I see this:

```
--- Process 4980 loaded C:\Python36_64\Lib\site-packages\PyQt5\Qt.pyd at 00007fff50b50000
--- Process 4980 unloaded DLL at 00007fff50b50000
```

That is relatively to the end, so the Qt.pyd seems to hate running under Nuitka here. It does normally load "PyQt5.QtCore" first thing, but it doesn't get there. That DLL is not even attempted to be loaded in the error case it seems.

**Comment by kayhayen** [comment]
Oh my goodness,

this works:

`/c/Python36_64/python_d.exe ../../../Py2C/bin/nuitka --python-debug --run --debug main.py`

This does not:
`/c/Python36_64/python ../../../Py2C/bin/nuitka --run --debug main.py`

That has no explanation, except that the .pyd loading my ignore something here for debug Python (--python-debug, the --debug is for Nuitka only), that it will not without.

Ok, so I think I got that one under control. The issue seems to be, that for accelerated mode, Nuitka loads itself only "python36.dll", whereas "Qt.pyd" tries to load "python3.dll", which will fail, unless already done by "python.exe".

As a workaround to not being able to specify where to load the DLLs from, ideally it would be the Python installation, Nuitka copies the python36.dll to the binary directory. That is ugly, and apparently not even enough.

I just noticed however, that in libs, there is a new "libpython36.a", that probably could be used with some success too (3.5 or higher). Or at least, Nuitka itself could go through "python3.lib" and then require the "python3.dll", although that would clearly be a downgrade in precision, as Nuitka will be very tied to the specific run time using internal details all the time.

So that one, would be another issue, and unrelated to yours. It is accelerated mode only, which matters to me though. Copying both DLLs seems sufficient. I am going to create that issue now.

**Comment by kayhayen** [comment]
I created this as #84 and the solution might be as simple as to copy more DLLs along, so that is a side show, but could affect standalone too. Recently, we removed the PATH changes, and in that, as well, the consideration of the binary directory.

So this part:

```
# Put the "Python.exe" first. At least for WinPython, they put the DLLs
# there.
path = [sys.prefix] + sys.path + path
```

The `sys.prefix` is therefore no longer in the search path of dependency walker, and was injected via PATH at the time. 

Although pretty likely the issue is being that the loading of Qt.pyd is wrongly overtaken by "Qt" directory (still need to check), it wouldn't find "python3.dll" by any means now, therefore making it impossible to load, at which point a fallback to Qt directory might kick in. That also needs to be checked, but right now I don't think it can work as it stands, and should fail to locate the "python3.dll" or at least after fixes.

As issue #84 may well change a lot in this area, considering to even link python DLL statically, as it seems possible nowadays, I want to defer this except for the part where there is doubt about what the import recursion is taking for Qt.pyd right now. Because that is very likely what is causing the issue for the star import in the issue title.

**Comment by kayhayen** [comment]
Ok, this is not the feared incompatibility for the import scan, but simply the hidden dependencies of Qt.PYD are numerous, and the error handling is bad, i.e. it will skip over import errors of PyQt5.QtCore and abort from there, but pretend everything is fine to the import call, not forwarding the exception given by its import call.

That is typical of low quality C extension code. Error handling is rare, but normally you get a segmentation fault or run time error, I am right now iterating over these errors (in `lib/hints.py` there is something that traces imports and with coming factory changes, their errors) and unfortunately one by one, I am adding these, until it will be enough to see them. 

This exists for all PyQt5 extension modules from a previous effort, where I am having a test to make a standalone distribution with just that extension module, and fixing the crashes. But maybe Qt.pyd is new, or more likely, the only one not crashing, so this escaped attention so far.

**Comment by brupelo** [comment]
@kayhayen Hiya, wow, it seems narrowing this one wasn't trivial at all, phew :) 

In any case, I've realized the way I'm creating the issues lasty, that is, providing reproducer steps + additional video showing you exactly how these kind of issues happen is quite an effective way of communication.

Btw, sorry I can't contribute with code or useful ideas for my opened issue but the fact I've got dozens of personal projects to handle as well and the fact than gaining a deep level of understanding of nuitka wouldn't be a 5 min job means becoming a code-contributor is at least atm a panacea. That said, opening issues like these ones, which expose really interesting real-world-cases is something I'm more than happy to continue doing :)

For instance, on many of my personal projects I tend to use the star operator when using meaty libraries like `pyqt, sympy, pyparsing, pyopengl....` but I do just use the star operator ON development/staging... when the project is ready to be moved to production I always try to refactor the whole thing and get rid of then, as using star operator is not considered to be a good practice on python-land.

On other cases, I'll just use the star operator wit no relative import packaging at all, as that will allow me to rewrite c++ qt/opengl code to python almost 1:1 :)

Anyway, that said, when you release the factory version is I'll check it out and report you back whether or not i find more issues like the reported one.

As usual, thanks for your hard job!
Keept it going :D

B.

**Comment by kayhayen** [comment]
I just verified, that "Python3.DLL" is indeed and as expected not found, but also not the "Python36.DLL" in case of "uninstalled" Python (which all my Python3 are, Python2 installers do not obey your wishes anyway), which is really bad.

But it would have to be that way, since the copying of that DLL near the binary is explicitly not done standalone mode. One solution would be to copy the DLLs so they can be found. But I will just undo the removal of "sys.prefix" I guess, since that was what made it work previously.

That means, we have a regression here from the fix currently being on factory, that removed the search for "sys.prefix". So I am going to be amending the commit on factory, rebasing later.

And yeah, these things for standalone are never easy, but easily confusing. When extension modules written by 3rd parties come into play, generally there is always something shady to be expected. I have lost way too much time on this already. But I was stupid in the sense that I didn't think of hidden dependencies more immediately.

Having the test case in the repo is very attractive to me as I can see all the details, instead of wondering what was left out. I will not follow your instructions, e.g. not use a virtualenv when I think it is not needed, or not standalone mode, when accelerated should show it, but it is good to go back to why things do work for me, when they do, and not for you, or even to find more issues as seen in this instance.

I will definitely prefer issues with that form of testcase over issues without.

Yours,
Kay

**Comment by brupelo** [comment]
@kayhayen Before considering a regression and not giving proper support to virtualenv anymore using just system-wide python and going the easy bad way :) . Are you sure you're using the latest virtualenv version (ie: just check pip install --upgrade virtualenv). 

Pointing this out cos few months ago I'd had some problems with pyqt5+virtualenv and I'd submitted a patch to virtualenv which is I think related to the problems you're talking about python3.dll and python36.dll. Anyway, look at this issue I'd [opened](https://github.com/pypa/virtualenv/pull/1083), the hotfix is living in pypi since few months ago, latest version atm should be `15.2.0` If I'm not mistaken.

**Comment by brupelo** [comment]
@kayhayen Kay, just to clarify, take a look to this [comparison](https://dl.dropboxusercontent.com/s/5fsq4zxx30x23zy/2018-05-11_01-21-53.mp4) between an old virtualenv version and the newest one (my patch included).

It makes no sense to give up on virtualenvs, as they will behave like a system-wide python  :) . I don't think giving just proper support on windows to users who don't use virtualenv is not the right way to go, for instance, think about pycharm users (which is quite a big community), they use virtualenv by de facto.

In any case, I understand your project your rules but... people like me who handle many many different projects tied to different requirements/python versions all over the disk are benefiting quite a lot on using virtualenvs. So I'd ask you kindly to think about reconsidering your decission of not supporting properly virtualenv anymore, as there is a big % of users in this side of the spectrum ;)

Yours.
Bruno

**Comment by kayhayen** [comment]
I have labeled the issues I think should be good now with "factory". If you can test them, @brupelo let me know of results, but I think they are good to release at least to develop.

**Comment by brupelo** [comment]
@kayhayen Kay, been testing for quite a while your latest factory and just let you know that now both pyqt test1 and test2 are [ok](https://github.com/brupelo/nuitka_tests/blob/master/report.txt) with `0.5.31rc1` (latest factory atm), awesome job! 

Glad you've finally made the right call here of not giving up with virtualenv ;) . Although tbh I understand sometimes when working on hobby projects like nuitka, the creator can be just interested to make the tools to be suitable for their particular workflow... I know that cos I've been already there few times :)

Out of curiosity, did you have an outdated version of virtualenv?

Anyway, I've found other issues but they are different to this one so later I'll be opening new tickets... Summing up, this ticket has been solved and I think we can close it.

NS: I've modified my little repo test a [bit](https://github.com/brupelo/nuitka_tests) and now each time you build can see how long nuitka will take to package.

**Comment by kayhayen** [comment]
@brupelo I am not against using virtualenv or intent on not supporting it. 

But when I try to get to a minimal reproducer, eliminating virtualenv is one of the steps I will make. To Nuitka, it is a complication of things as often site.py is doing even more magic than normally. Some bugs therefore will only show inside virtualenv. When they show outside too, that removes some potential sources.

For all your error reports it's a great thing. It makes it easier to be reproducible and independent and cover specific package configurations, if those are the issue. But when they are not, I am not sticking to it. I will try to use your reproducer as minimally as possible.

And just to be clear. I definitely welcome the reproducer to use virtualenv. It's easy for me to find out if that is a contributing factor or not, by not activating it.

I will typically close issues once I make a stable release or maybe even if pre-release with them, removing "factory" tag, once I have a pre-release with it. For me it's also a nice guidance when to add something to the changelog about it.

**Comment by brupelo** [comment]
@kayhayen Thanks to clarify it, makes total sense! In any case, with my previous posts I just wanted to point out than virtualenv is used widely in the python community so giving a good support to it will ensure quite a lot of more people will get interested on nuitka as well.

Btw, talking about closing issues just let you know I've closed one few days [ago](https://github.com/kayhayen/Nuitka/issues/73) as I got the "Close and comment" button available but from now on I'll leave this to you so it becomes easier to write changelogs out of them, manage yourself and so on... ;) . Anyway, as said before, this one is solved, so... moving on
