### ISSUE TITLE
Standalone: PyOpengl plugins not included automatically

### ISSUE THREAD

**Issue by brupelo** [kayhayen/Nuitka#86]
**Nuitka version:**

    (venv) D:\sources\personal\python\apps\nuitka_tests\test5\main.dist>nuitka --version
    0.5.31rc1
    3.6.4 (v3.6.4:d48eceb, Dec 19 2017, 06:04:45) [MSC v.1900 32 bit (Intel)]
    D:\sources\personal\python\apps\nuitka_tests\venv\Scripts\python.exe

**Steps:**

 - git clone https://github.com/brupelo/nuitka_tests && cd nuitka_tests
 - venv.bat
 - cd test5
 - build.bat
 - cd main.dist && main.exe

**Traceback:**

Building time took me 488.884s, when trying to run main.dist\main.exe you'll get:

    (venv) D:\sources\personal\python\apps\nuitka_tests\test5\main.dist>main.exe
    Traceback (most recent call last):
      File "D:\sources\personal\python\apps\nuitka_tests\test5\main.dist\main.py", line 3, in <module>
      File "<frozen importlib._bootstrap>", line 971, in _find_and_load
      File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
      File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
      File "D:\sources\personal\python\apps\nuitka_tests\test5\main.dist\OpenGL\arrays\__init__.py", line 19, in <module OpenGL.arrays>
      File "<frozen importlib._bootstrap>", line 971, in _find_and_load
      File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
      File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
      File "D:\sources\personal\python\apps\nuitka_tests\test5\main.dist\OpenGL\arrays\arraydatatype.py", line 4, in <module OpenGL.arrays.arraydatatype>
      File "<frozen importlib._bootstrap>", line 971, in _find_and_load
      File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
      File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
      File "D:\sources\personal\python\apps\nuitka_tests\test5\main.dist\OpenGL\raw\GL\_types.py", line 129, in <module OpenGL.raw.GL._types>
      File "<frozen importlib._bootstrap>", line 971, in _find_and_load
      File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
      File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
      File "D:\sources\personal\python\apps\nuitka_tests\test5\main.dist\OpenGL\platform\__init__.py", line 35, in <module OpenGL.platform>
      File "D:\sources\personal\python\apps\nuitka_tests\test5\main.dist\OpenGL\platform\__init__.py", line 29, in _load
    TypeError: 'NoneType' object is not callable

You can find the log available [here](https://github.com/brupelo/nuitka_tests/blob/master/test5/log.txt).

Any idea about this one?

**Comment by kayhayen** [comment]
@brupelo Stop vandalizing the issue tracker, thank you.

**Comment by brupelo** [comment]
@kayhayen Not vandalizing anything, closed this one as it's working to me as I'm not using nuitka builtin freezer anymore and using my own freezer. Just closed issues I won't be contributing anymore... how's that supossed to be vandalizing?

**Comment by kayhayen** [comment]
Because I don't care if it's working for you, but if it's working.

**Comment by kayhayen** [comment]
I just pushed a change to factory that makes it load the platform plugins automatically, depending on the OS.

I still would love a better example than "import OpenGL", one that that shows in a headless system things work, but this might be workable.
